const projectData = {
    invoicing: {
        milestones: [
            {
                milestone: 'Phase 1 - Requirements Gathering',
                plannedInvoiceDate: '2025-01-31',
                actualInvoiceDate: '2025-02-02',
                plannedPaymentDate: '2025-02-28',
                actualPaymentDate: '2025-03-05',
                invoiceAmount: 15000,
                paymentStatus: 'paid',
            },
            {
                milestone: 'Phase 2 - Power Apps Portal Development',
                plannedInvoiceDate: '2025-03-15',
                actualInvoiceDate: '2025-03-18',
                plannedPaymentDate: '2025-04-12',
                actualPaymentDate: null,
                invoiceAmount: 22500,
                paymentStatus: 'pending',
            },
            {
                milestone: 'Phase 3 - Power Automate Workflow Implementation',
                plannedInvoiceDate: '2025-04-30',
                actualInvoiceDate: null,
                plannedPaymentDate: '2025-05-28',
                actualPaymentDate: null,
                invoiceAmount: 30000,
                paymentStatus: 'pending',
            },
            {
                milestone: 'Phase 4 - Integration & Testing',
                plannedInvoiceDate: '2025-05-31',
                actualInvoiceDate: null,
                plannedPaymentDate: '2025-06-28',
                actualPaymentDate: null,
                invoiceAmount: 45000,
                paymentStatus: 'pending',
            },
            {
                milestone: 'Phase 5 - Deployment & Training',
                plannedInvoiceDate: '2025-06-30',
                actualInvoiceDate: null,
                plannedPaymentDate: '2025-07-28',
                actualPaymentDate: null,
                invoiceAmount: 37500,
                paymentStatus: 'pending',
            },
        ],
    },
    profitability: {
        contractValue: 150000,
        estimatedCost: 75000,
        revenueRecognized: 75000,
        costIncurred: 40000,
        utilization: '75%',
        invoicedToDate: 37500,
        paymentsReceived: 15000,
    },
    schedule: {
        tasks: [
            { task: 'Requirements Gathering', status: 'Complete', plannedStart: '2025-03-03', plannedEnd: '2025-03-10', actualStart: '2025-03-03', actualEnd: '2025-03-17', completion: '100%', resources: 'PM, BA', notes: '' },
            { task: 'Power Apps Portal Design', status: 'In Progress', plannedStart: '2025-03-10', plannedEnd: '2025-03-24', actualStart: '2025-03-17', actualEnd: null, completion: '65%', resources: 'PA Dev', notes: 'Minor delays in UI design.' },
            { task: 'Power Automate Workflow Dev', status: 'In Progress', plannedStart: '2025-03-24', plannedEnd: '2025-05-05', actualStart: null, actualEnd: null, completion: '40%', resources: 'PA Dev', notes: '' },
            { task: 'Integration with Legacy System', status: 'Planned', plannedStart: '2025-04-21', plannedEnd: '2025-05-15', actualStart: null, actualEnd: null, completion: '0%', resources: 'PA Dev, Integration Spec', notes: '' },
            { task: 'User Acceptance Testing', status: 'Planned', plannedStart: '2025-05-16', plannedEnd: '2025-05-31', actualStart: null, actualEnd: null, completion: '0%', resources: 'Client, PM', notes: '' },
            { task: 'Deployment & Training', status: 'Planned', plannedStart: '2025-06-01', plannedEnd: '2025-06-30', actualStart: null, actualEnd: null, completion: '0%', resources: 'PM, Trainer', notes: '' },
        ],
    },
    raidLog: [
        {
            id: 'R-001',
            type: 'Risk',
            title: 'Legacy System Integration Delay',
            description: 'Potential delay in integrating with the client\'s legacy invoicing system due to technical complexities or lack of documentation.',
            impact: 'High',
            likelihood: 'Medium',
            status: 'Open',
            owner: 'Integration Lead',
            dateIdentified: '2025-03-15',
            mitigation: 'Dedicated integration team assigned; proactive communication with client IT; contingency plan with manual data entry if needed.',
            targetResolutionDate: '2025-04-30',
            lastUpdated: '2025-04-05',
            comments: 'Initial assessment indicates higher than expected complexity.',
        },
        {
            id: 'I-002',
            type: 'Issue',
            title: 'UAT Resource Unavailability',
            description: 'Key client stakeholders for User Acceptance Testing might have conflicting schedules, leading to delays in testing.',
            impact: 'Medium',
            likelihood: 'High',
            status: 'In Progress',
            owner: 'PM',
            dateIdentified: '2025-03-22',
            mitigation: 'Multiple UAT sessions planned; flexible scheduling options offered; backup testers identified.',
            targetResolutionDate: '2025-05-31',
            lastUpdated: '2025-04-08',
            comments: 'Confirming availability for the week of May 19th.',
        },
        {
            id: 'A-003',
            type: 'Action',
            title: 'Finalize Power Automate Workflow Design',
            description: 'Need to finalize the detailed design document for the invoice processing workflow in Power Automate.',
            impact: 'Medium',
            likelihood: 'High',
            status: 'Complete',
            owner: 'PA Dev Lead',
            dateIdentified: '2025-03-05',
            mitigation: 'Design workshop conducted; document reviewed and approved by stakeholders.',
            targetResolutionDate: '2025-03-12',
            lastUpdated: '2025-03-12',
            comments: 'Design document signed off.',
        },
        {
            id: 'D-004',
            type: 'Decision',
            title: 'Choice of Authentication Method',
            description: 'Need to decide on the final authentication method for the Power Apps portal (Azure AD vs. custom).',
            impact: 'Low',
            likelihood: 'High',
            status: 'Closed',
            owner: 'Solution Architect',
            dateIdentified: '2025-03-01',
            mitigation: 'Technical evaluation completed; recommendation presented and approved.',
            targetResolutionDate: '2025-03-08',
            lastUpdated: '2025-03-08',
            comments: 'Azure AD selected for its security features.',
        },
    ],
    ragStatus: {
        scope: 'yellow',
        schedule: 'green',
        cost: 'green',
        risk: 'yellow',
        bug: 'red',
    },
    bug: {
        openBugs: 15,
        newThisWeek: 5,
        resolvedThisWeek: 3,
        criticalOpen: 2,
    },
};
